### ISSUE TITLE
"Crashlytics" does not conform to protocol "CrashlyticsProtocol"

### ISSUE THREAD

**Issue by humblehacker** [AnthonyMDev/CrashlyticsRecorder#1]
I'm finally getting around to trying this out, but I'm running into this issue compiling:

```
"Crashlytics" does not conform to protocol "CrashlyticsProtocol"
CrashlyticsRecorder.CrashlyticsProtocol:10:17: 
Protocol requires function 'recordError(_:withAdditionalUserInfo:)' with type '(NSError, withAdditionalUserInfo: [String : AnyObject]?) -> ()'
```

I suspect the Crashlytics class has changed since this code was written.  Are you still using this in your own code? And if so, do you have an updated version?

**Comment by AnthonyMDev** [comment]
What version of `Crashlytics` are you using? I've not seen this error yet. I've also been informed that `Crashlytics` now supports dynamic frameworks, so this library shouldn't be needed anymore.

**Comment by humblehacker** [comment]
Thanks for the reply.  I'm on the latest, [3.7.0](https://docs.fabric.io/ios/changelog.html#id1).  I haven't heard about Crashlytics/Fabric being provided as a dynamic framework. That would be great! Can you point me to any details online?

**Comment by AnthonyMDev** [comment]
I actually don't see anything about the change on their change log. To be fair, I haven't confirmed that this is true myself. It was just told to me by someone else recently. 

It's likely that there was a change in the most recent version of `Crashlytics` that was API braking. I'll try to carve out sometime tomorrow afternoon to get this fixed. If you need it before then, a PR is always appreciated! It should be a pretty easy fix, assuming they didn't completely change all of their API's.

**Comment by AnthonyMDev** [comment]
@humblehacker I've looked into it, and this library is still working just fine for me. There is no changes that are stopping it from conforming. 

Have you followed the directions in the README? You do need to include the [`CrashlyticsAdapter.swift`](https://github.com/AnthonyMDev/CrashlyticsRecorder/blob/master/Example/Tests/CrashlyticsAdapter.swift) file in your project.

**Comment by AnthonyMDev** [comment]
@humblehacker Can you please confirm that you have included the adapter in your code and the problem persists? If I don't hear back from you, I'm going to close this issue.

Thanks
