### ISSUE TITLE
Add 2.3.0 to CocoaPods repo

### ISSUE THREAD

**Issue by bonebox** [AnthonyMDev/CrashlyticsRecorder#12]
Can you please add the 2.3.0 podspec to the master CocoaPods repo, thanks!

**Comment by AnthonyMDev** [comment]
@JettF can you handle this?

**Comment by JettF** [comment]
Yeah, I can handle it.

**Comment by JettF** [comment]
@bonebox 2.3.0 has been push to the trunk! Thank you for your patience. If you have any issues with it, let me know. :)

**Comment by bonebox** [comment]
Thanks!
