### ISSUE TITLE
Include in a objective C private pod

### ISSUE THREAD

**Issue by fabiomassimo** [AnthonyMDev/CrashlyticsRecorder#2]
I'm trying to use Crashlytics Recorder to log errors from my private pod. In my podspec I'm using following:

``` ruby
s.dependency 'CrashlyticsRecorder'
```

Unfortunately, from my objective C file in my private pod I'm not able to add the `Recorder` to access the method that I need.

How should I proceed?

**Comment by AnthonyMDev** [comment]
Have you added `@import CrashlyticsRecorder` to your Objective-C file?

**Comment by fabiomassimo** [comment]
Yes I tried but `CrashlyticsRecorder` is still not available ¯_(ツ)_/¯

**Comment by AnthonyMDev** [comment]
I'm not sure why this is happening given the information you have provided. Can you provide a test project that I can recreate the issue in?

**Comment by AnthonyMDev** [comment]
Since I can't reproduce this and have not received a response from you, I'm going to close this ticket. Please feel free to re-open if you can provide more information!
