### ISSUE TITLE
Does not conform to Protocol in Swift 3

### ISSUE THREAD

**Issue by gokeji** [AnthonyMDev/CrashlyticsRecorder#5]
My team has transitioned to Swift 3, using XCode 8 Beta 4.

Due to the naming convention changes in Swift 3, the obj-C classes are bridged over to Swift with a slightly different signature now. I'm seeing protocol conformation issues that look like this.
![screen shot 2016-08-04 at 12 58 15 pm](https://cloud.githubusercontent.com/assets/734461/17411822/cdc88320-5a47-11e6-8047-4e5f75db1568.png)

I couldn't quite figure out what the correct protocol should look like in Swift 3 now. Any help is appreciated. Thanks.

**Comment by gokeji** [comment]
Actually, I figured it out. I needed to add a `_` in front of the arguments of each protocol `func` definition. E.g.:
`
func setUserIdentifier(_ identifier: String?)
`

And then it works like a charm again :)

**Comment by AnthonyMDev** [comment]
@gokeji Thanks. Would you be willing to make a PR with the changes you've made?
